version: '3.9'
services:
  mtgtable:
    image: docker.io/library/mtgtable
    networks:
      - nginx_default
    ports:
      - "3030:3030"
    restart: 'on-failure:10'
    container_name: majiq

networks:
  nginx_default:
    external: true
